// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import BookshelfController from "./bookshelf_controller"
application.register("bookshelf", BookshelfController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import FocusSoundController from "./focus_sound_controller"
application.register("focus-sound", FocusSoundController)

import FocusTimerController from "./focus_timer_controller"
application.register("focus-timer", FocusTimerController)

import FocusUiController from "./focus_ui_controller"
application.register("focus-ui", FocusUiController)

import FragmentUploadController from "./fragment_upload_controller"
application.register("fragment-upload", FragmentUploadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import MailboxTabsController from "./mailbox_tabs_controller"
application.register("mailbox-tabs", MailboxTabsController)

import MemoController from "./memo_controller"
application.register("memo", MemoController)

import PaletteController from "./palette_controller"
application.register("palette", PaletteController)

import ProfileTabsController from "./profile_tabs_controller"
application.register("profile-tabs", ProfileTabsController)

import ReadMoreController from "./read_more_controller"
application.register("read-more", ReadMoreController)

import TopTabsController from "./top_tabs_controller"
application.register("top-tabs", TopTabsController)
