# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"

pin "controllers/application", to: "controllers/application.js"
pin "controllers/hello_controller", to: "controllers/hello_controller.js"
pin "controllers/color_picker_controller", to: "controllers/color_picker_controller.js"
pin "controllers/audio_player_controller", to: "controllers/audio_player_controller.js"
pin "controllers/focus_sound_controller", to: "controllers/focus_sound_controller.js"
pin "controllers/clipboard_controller", to: "controllers/clipboard_controller.js"
pin "controllers/read_more_controller", to: "controllers/read_more_controller.js"
pin "controllers/drawer_controller", to: "controllers/drawer_controller.js"
pin "controllers/autosave_controller", to: "controllers/autosave_controller.js"
pin "controllers/bookshelf_controller", to: "controllers/bookshelf_controller.js"
pin "controllers/chat_controller", to: "controllers/chat_controller.js"
pin "controllers/focus_timer_controller", to: "controllers/focus_timer_controller.js"
pin "controllers/memo_controller", to: "controllers/memo_controller.js"
pin "controllers/mailbox_tabs_controller", to: "controllers/mailbox_tabs_controller.js"
pin "controllers/handwriting_controller", to: "controllers/handwriting_controller.js"
pin "controllers/fragment_upload_controller", to: "controllers/fragment_upload_controller.js"
pin "controllers/tutorial_controller", to: "controllers/tutorial_controller.js"
pin "controllers/top_tabs_controller", to: "controllers/top_tabs_controller.js"
pin "controllers/image_preview_controller", to: "controllers/image_preview_controller.js"
pin "controllers/install_guide_controller", to: "controllers/install_guide_controller.js"
pin "controllers/profile_tabs_controller", to: "controllers/profile_tabs_controller.js"
pin "controllers/palette_controller", to: "controllers/palette_controller.js"

pin "entrypoint", to: "controllers/index.js"